//                          AUTOCORE SOFTWARE, INC.
//                    $$PRODUCTNAME$$ SOFTWARE LICENSE AGREEMENT
//
//        PLEASE READ THE FOLLOWING LICENSE AGREEMENT BEFORE INSTALLING AND
//        USING
// THE $$PRODUCTNAME$$ SOFTWARE PROGRAM (THE "SOFTWARE") ASSOCIATED WITH THIS
// AGREEMENT.
//
//        CLICKING ON THE "ACCEPT" OR "YES" BUTTON IN RESPONSE TO THE ELECTRONIC
// LICENSE AGREEMENT ENQUIRY AS TO ACCEPTANCE OF THE TERMS OF THIS LICENSE
// AGREEMENT, INSTALLING OR DOWNLOADING THE SOFTWARE, INDICATES ACCEPTANCE OF
// AND AGREEMENT TO, AND LEGALLY BINDS YOU, YOUR EMPLOYER (COLLECTIVELY THE
// "CUSTOMER"), AND AUTOCORE SOFTWARE, INC., A NANJING CORPORATION, ON ITS OWN
// BEHALF AND ON BEHALF OF ITS SUBSIDIARIES (COLLECTIVELY "AUTOCORE") TO THE
// TERMS AND CONDITIONS OF THIS LICENSE AGREEMENT (INCLUDING ANY TERMS,
// CONDITIONS AND RESTRICTIONS CONTAINED IN ANY ORDER RELATING TO THE SOFTWARE).
// IF THE CUSTOMER DOES NOT ACCEPT AND AGREE TO THE TERMS AND CONDITIONS OF THIS
// LICENSE AGREEMENT THEN THE CUSTOMER SHOULD NOT DOWNLOAD, INSTALL, OR
// OTHERWISE USE THE SOFTWARE.
//
//        THE RIGHT TO USE THE SOFTWARE IS CONDITIONAL UPON ACCEPTANCE OF THIS
// AGREEMENT, UNLESS THE CUSTOMER HAS ENTERED INTO A WRITTEN AND DULY SIGNED
// LICENSE AGREEMENT WITH AUTOCORE, IN WHICH CASE SUCH SIGNED LICENSE AGREEMENT
// WILL GOVERN THE CUSTOMER'S USE OF THE SOFTWARE.
//
//        THIS LICENSE AGREEMENT SHALL APPLY EVEN WHERE AUTOCORE PERFORMS ITS
// CONTRACTUAL OBLIGATIONS WITHOUT RESERVATION DESPITE BEING AWARE THAT THE
// CUSTOMER HAS SUBMITTED TERMS AND CONDITIONS THAT ARE INCONSISTENT WITH OR IN
// ADDITION TO THE TERMS AND CONDITIONS CONTAINED IN THIS LICENSE AGREEMENT.
//
// 1. Certain Defined Terms.  For purposes hereof, the terms provided below,
// when used anywhere in this Agreement with initial capital letters, will have
// the respective meanings as set forth below:
//        1.1 "Documentation" means the then-current printed and digital user
// manual(s), instructions, on- line help files and technical documentation for
// the Programs (including releases) made available by AUTOCORE, and any
// materials or deliverables that AutoCore provides to Customer as part of this
// Agreement, or in the course of providing the Software Support to the
// Customer.
//        1.2 "Evidential Output" means that part of the Output that is used for
// evidential, validation or audit purposes.
//        1.3 "Output" shall mean the data in electronic or other format
// containing the results generated by using the Software.
//        1.4 "Program(s)" means the machine-readable object code of the
//        computer
// software program or programs described in one or more invoices to this
// Agreement, including any additional releases of such programs as are made
// available by AutoCore to Customer from time to time.
//        1.5 "Reports" means the reports generated by the Software.
//        1.6 "Software" means, collectively, the Program and the Documentation.
//        1.7 "Software Support" means technical support and maintenance
//        services
// for the Program licensed under this Agreement as described in AUTOCORE's
// then-current Software Support policy, and any new releases to the Software
// for which Customer is paying the Software Support fee.
//
// 2. Grant of License.
//        2.1 Grant of License.  In consideration of Customer's payment of the
// license fee, and subject to the terms and conditions of this Agreement,
// AutoCore grants to Customer a limited, non-sub licensable, non-exclusive,
// non-transferable, fully-paid (upon payment of the fees set forth in Section 4
// of this Agreement) license for Customer's authorized users to: (a) install
// and use the Software ordered by Customer in accordance with the Documentation
// for Customer's own direct internal business purposes, and subject to any
// limitation on use specified in this Agreement; (b) install and use the
// Documentation solely in conjunction with and in support of Customer's
// licensed use of the Software; and (c) make the number of exact copies of the
// Software as required for archival and back-up purposes, and a reasonable
// number of copies of the Documentation to support the licensed number of
// users, provided that each copy of the Software and the Documentation retains
// all copyright and other proprietary notices included in the original copy
// provided by AutoCore to the Customer.  AutoCore hereby reserves all rights in
// and to the Software that are not specifically granted by this Agreement.
//        2.2 Restrictions on License Grant.  Except as expressly provided in
// Section 2.1 above, Customer will not, either directly or indirectly, cause,
// instruct, direct, or permit any other party to: (a) reverse engineer,
// translate, disassemble, decompile, sell, rent, lease, manufacture, adapt,
// create derivative works from, or otherwise modify or distribute the Software
// or the Documentation, or any part thereof; (b) copy, in whole or in part, the
// Software or the Documentation; (c) delete any copyright, trademark, patent or
// other notices of proprietary rights of AutoCore or other parties as they
// appear anywhere in or on the Software or Documentation; or (d) tamper with,
// or attempt to tamper with, or circumvent or disable, or attempt to circumvent
// or disable, any license key or other limiting function delivered with the
// Software, or otherwise attempt to gain access to functionality or capacity
// that is not validly licensed by Customer.  Customer will not remove or
// otherwise alter any proprietary notices or labels from the Programs,
// Documentation, or any portion thereof.
//        2.3 Output.  Customer shall be entitled to provide the Output, Report,
// and/or Evidential Output to parties who are not authorized users or third
// party agents solely for the purpose of audit, quality assurance, validation,
// or evidential purposes.  The Customer shall not provide the Software, Output,
// Report, and/or Evidential Output to parties who are not authorized users or
// third party agents of the Customer for operating the Software, including,
// without limitation, operating the Software in order to correct the target
// Software.  Without the prior written consent of AUTOCORE, the Customer shall
// not commercialize in any way the Output, Evidential Output, and/or Reports
// including, without limitation, by licensing, sub-licensing, assigning, or
// sub-contracting the use of the Output, Evidential Output, or Reports to any
// party other than the authorized users or third party agents.  The Customer
// shall not incorporate the Output, Evidential Output, or Reports in any
// application or tool of the Customer or a third party application or tool.  In
// the event that AutoCore consents in writing to such use of the Output,
// Evidential Output, or Reports, AutoCore shall be entitled to charge a fee to
// be paid by the Customer of an amount to be determined by AutoCore in its sole
// discretion in respect of each and every use of the Output, Reports, or
// Evidential Output by a party who is not an authorized user or third party
// agent other than for the purposes of audit, quality assurance, or validation
// or evidential purposes.
//        2.4 Compliance with Laws; Export Control.  Customer, on behalf of
//        itself
// and its Affiliates, agrees to comply fully with all applicable laws,
// statutes, regulations, rules, ordinances, codes, and standards relating to
// any export controls and economic sanctions laws of the United States or
// abroad.  Customer acknowledges that the Software is of United States origin
// and is subject to the Export Administration Regulations (the "EAR")
// administered by the U.S. Department of Commerce's Bureau of Industry and
// Security ("BIS"), and the laws and regulations governing economic sanctions
// and embargoes administered by the U.S. Department of the Treasury's Office of
// Foreign Assets Control ("OFAC"). Accordingly, any use, transshipment, or
// diversion of the Software contrary to applicable export control laws or
// sanctions laws is prohibited.  Customer warrants and covenants that: (1)
// Customer and its Affiliates will not export, re-export, re-sell, provide
// access to, or otherwise transfer the Subscription Services or related
// technology with knowledge that a violation of the U.S. law, the EAR, or the
// terms of any order, license, license exception, or other authorization issued
// under the EAR has occurred, is about to occur, or is intended to occur in
// connection with the item; and (2) Customer and its Affiliates will not
// export, re-export, re-sell, provide access to, or otherwise transfer the
// Subscription Services into any country or region subject to comprehensive
// economic sanctions (i.e., currently Cuba, Iran, North Korea, Syria, and the
// Crimea Region of Ukraine).  Customer further represents that: (a) Customer
// and its Affiliates are not, and are not acting on behalf of, (i) any natural
// person or entity who is a citizen, national, or resident of, or who is
// controlled by, the government of any country to which the United States has
// prohibited export, reexport, or transfer of the Subscription Services or
// related technology, or (ii) any natural person or entity listed on OFAC's
// list of Specifically Designated Nationals and Blocked Persons or the
// Consolidated Sanctions List, or BIS's Denied Persons List, Entity List, or
// Unverified List; and (b) Customer and its Affiliates will not permit the
// Subscription Services to be used for any purposes prohibited by law,
// including but not limited to any prohibited development, design, manufacture,
// or production of missiles or nuclear, chemical, or biological weapons.
// Customer shall exercise diligent efforts to ensure its and its Affiliates'
// compliance with this Section 2.4.
//        2.5 Federal Government End Use Provisions.  AutoCore may provide the
// Software for ultimate federal government end use solely in accordance with
// the following: Government technical data and software rights related to the
// Software include only those rights customarily provided to the public as
// defined in this Agreement.  This customary commercial license is provided in
// accordance with FAR 12.211 (Technical Data) and FAR 12.212 (Computer
// Software), and the Department of Defense transactions, DFAR 252.227-7015
// (Technical Data - Commercial Items) and DFAR 227.7202-3 (Rights in Commercial
// Computer Software or Computer Software Documentation).  If a government
// agency has a need for rights not conveyed under these terms, it must
// negotiate with AutoCore to determine if there are acceptable terms for
// transferring such rights, and a mutually acceptable written addendum
// specifically conveying such rights.
//        2.6 Verification.  Upon providing Customer with reasonable advance
// notice, and subject to AUTOCORE's obligations provided in Section 8 of this
// Agreement, no more than one time during any 12-month period, AutoCore may
// audit Customer's use of the Software to verify Customer's compliance with the
// terms of this Agreement.  Any such audit will be restricted in scope, manner,
// and duration to that which is reasonably necessary to achieve its purpose,
// will be conducted during regular business hours at Customer's facilities, and
// AutoCore will not unreasonably interfere with Customer's business activities.
// Customer will provide AUTOCORE's auditors access to the relevant Customer
// records, including, without limitation, unaltered license server log files,
// and access to Customer's facilities.  Customer will be liable for promptly
// remedying any underpayments revealed during the audit at the then-current
// price per authorized user.  If the audit reveals a failure to materially
// comply with terms and conditions of this Agreement, and/or if the audit
// reveals an underpayment of at least ten percent (10%) or more that the
// Customer is currently paying, Customer will also be liable for the costs of
// the audit in addition to any unpaid fees, or other damages, and any other
// remedies available to AutoCore in this Agreement.
//        2.7 Free or "Open Source" Components.  The Software may include
// components, including, without limitation, programs, applications, tools,
// utilities, libraries and other programming code) that are made available from
// third parties under a free or open source licensing model ("Open-Source
// Components").  Open-Source Components included in the Software are
// redistributed by AutoCore under the terms of the applicable Open Source
// Components license for such Open Source Component.  Your receipt of the Open
// Source Components will neither enlarge nor curtail your rights or obligations
// under the license applicable to such Open Source Component.  Copies of the
// licenses for the Open-Source Components that are included with the Software
// are included with, or referenced in, the Documentation.
//        2.8 Affiliates and Third Party Agents.  Notwithstanding anything to
//        the
// contrary herein, the rights granted to Customer hereunder may be exercised by
// any natural person or entity that directly or indirectly, controls or is
// controlled by or is under common control with the Customer (each such party
// an "Affiliate"), and/or by independent contractors performing services on
// behalf of Customer and/or such Affiliates, provided that Customer shall
// remain responsible at all times for such Affiliates' and independent
// contractors' adherence to all applicable terms and conditions of this
// Agreement and shall be primarily liable for any breach of this Agreement by
// such Affiliate and/or independent contractor.
//
// 3. Delivery; Fees; Payment; Taxes.
//        3.1 Acceptance of Software.  The Software shall be deemed to be
//        accepted
// upon delivery of the Software and Documentation to Customer.
//        3.2 Fees.  License fees and Software Support fees will be as set forth
// on the applicable invoice.  All license fees and Software Support fees that
// are invoiced to Customer will be payable by Customer in United States
// Dollars, unless otherwise billed in another currency as provided in the
// invoice.
//        3.3 Payment.  Payment terms are as specified in the applicable
//        invoice.
// If Customer fails to pay any amounts due under this Agreement by the due
// date, AutoCore will have the right to charge interest at a rate equal to the
// lesser of 1.5% per month, or the maximum rate permitted by applicable law,
// until Customer pays all amounts due.
//        3.4 Taxes.  All License and Software Support fees are exclusive of all
// sales, value added taxes, goods and services taxes, withholding taxes,
// customs duties, or similar taxes, duties, and charges.  Such taxes, duties,
// and charges shall be incremental to any License and Software Support fees and
// shall be payable by Customer in accordance with applicable law.
//        3.5 Purchase Orders.  Unless otherwise agreed to in writing between
// Customer and AUTOCORE, the acceptance of any order placed by Customer for the
// Software or Documentation is expressly made conditional upon Customer's
// acceptance of and agreement to the terms and conditions contained herein and
// AutoCore agrees to furnish the Software and Documentation only upon these
// terms and conditions and not on the terms and conditions contained in
// Customer's purchase order.  The terms and conditions on the reverse side of a
// Customer purchase order and on any AutoCore order acknowledgment form (if
// any) are of no force and effect.
//
// 4. Limited Warranties and Disclaimers.
//        4.1 Limited Warranty.  AutoCore warrants that for a period of 60 days
// after the receipt of the Software, the Program will perform substantially in
// accordance with its Documentation.  AutoCore does not warrant, however, that
// Customer's use of the Software will be uninterrupted, that the operation of
// the Software will be error-free, that the Software will meet Customer's
// requirements or that all errors will be corrected.  Customer assumes the
// entire risk as to the results and output of the Software.  If during the
// warranty period, as defined above, the Software fails to perform in
// accordance with the warranty, AutoCore shall use reasonable commercial
// efforts to correct the failure of the Software to perform in accordance with
// the warranty.  If AutoCore is unable to correct the failure within a
// reasonable time, AutoCore shall refund the purchase price of the Software.
//        4.2 Termination of Warranty.  The above limited warranty will not
//        apply
// to: (i) any defects caused by the combination, operation, or use of the
// Program with software, hardware, or other materials not provided by AUTOCORE;
// (ii) the Software being modified by any party other than AUTOCORE; and (iii)
// any use of the Software that does not conform to AUTOCORE's requirements as
// set forth in the documentation.
//        4.3 DISCLAIMER OF WARRANTIES.  EXCEPT AS EXPRESSLY SET FORTH IN
//        SECTION
// 4.1, THE SOFTWARE IS PROVIDED "AS IS," AND AutoCore MAKES NO OTHER
// REPRESENTATIONS OR WARRANTIES, AND AUTOCORE, ON BEHALF OF ITSELF AND ITS
// AFFILIATES, DISCLAIMS ALL REPRESENTATIONS, WARRANTIES, AND CONDITIONS
// RELATING TO THE SOFTWARE, OR OTHER SUBJECT MATTER OF THIS AGREEMENT, WHETHER
// ORAL OR WRITTEN, EXPRESS OR IMPLIED, ARISING FROM COURSE OF DEALING, COURSE
// OF PERFORMANCE, OR USAGE IN TRADE, OR OTHERWISE, INCLUDING, WITHOUT
// LIMITATION, ANY WARRANTY OF TITLE, NONINFRINGEMENT, MERCHANTABILITY, OR
// FITNESS FOR A PARTICULAR PURPOSE.  AutoCore DOES NOT MAKE ANY WARRANTY WITH
// RESPECT TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SOFTWARE.  TO
// THE EXTENT THAT AutoCore IS NOT PERMITTED BY APPLICABLE LAW TO DISCLAIM ANY
// WARRANTY PROVIDED HEREIN, THE SCOPE AND DURATION OF SUCH WARRANTY SHALL BE
// THE MINIMUM REQUIRED UNDER SUCH LAW.
//
// 5. Intellectual Property Ownership; Intellectual Property Infringement.
//        5.1 Intellectual Property.  Customer acknowledges and agrees that it
// obtains no ownership rights in the Programs, Documentation, or the Software
// Support under the terms of this Agreement, and that AutoCore has and retains
// all right, title, interest, and ownership, including any and all intellectual
// property rights, in and to the Programs, Documentation, and Software Support,
// and in any copies, improvements, enhancements, or updates of the Programs and
// the Documentation, whether made by Customer or AUTOCORE.  As between AutoCore
// and Customer, AutoCore owns all rights, title, interest, ownership, and
// proprietary rights in and to the Programs, Documentation, and all related
// intellectual property therein.  AUTOCORE's rights include, but are not
// limited to, all copies of the Programs, Documentation, and any patent rights
// (including but not limited to patent applications and disclosures),
// copyrights, trademark rights, trade secret rights, and any other intellectual
// property right recognized in any country or jurisdiction in the world.  The
// Software is protected by United States laws, laws of other nations, and
// international treaty provisions.  The Programs, any license keys to the
// Programs, and the Documentation constitute and embody valuable confidential
// information and trade secret information of AUTOCORE, and Customer will
// secure and protect such confidential information and trade secret information
// consistent with AUTOCORE's rights therein, and will not disclose such
// confidential information and trade secret information to any third party.
//        5.2 Claim of Intellectual Property Infringement.  Notwithstanding any
// other provision of this Agreement, AutoCore will defend, or settle at its own
// expense, any action brought against Customer to the extent that it is based
// on a claim that any Software supplied by AutoCore hereunder infringes any
// third party intellectual property right (an "Infringement Claim"), and
// indemnify Customer and its officers, directors, shareholders, employees,
// accountants, attorneys, agents, Affiliates, against fines, penalties, costs,
// damages and expenses (including reasonable legal fees) finally awarded
// against Customer by a court of competent jurisdiction, or agreed to in a
// written settlement agreement by AUTOCORE, arising out of such Infringement
// Claim.  AUTOCORE's obligation to indemnify Customer pursuant to this
// Section 6.2 is subject to the following conditions: (a) Customer must give
// AutoCore prompt written notice of any Infringement Claim; (b) Customer must
// provide, at AUTOCORE's expense, reasonable information and assistance in
// connection with the defense and settlement of such Infringement Claim; and
// (c) Customer agrees in writing with AutoCore that AutoCore has sole control
// of the settlement or defense of such Infringement Claim.
//        5.3 Notwithstanding the foregoing, AutoCore will have no obligation
// under Section 6.2 or otherwise with respect to any infringement claim based
// upon: (i) any use of the Software not in accordance with this Agreement or
// the Documentation; (ii) any use of the Software in combination with other
// products, equipment, software, or data not supplied by AutoCore where the
// combination gives rise to the claim; (iii) use of the Software in conjunction
// with Customer data where use with such data gives rise to the claim; (iv)
// Customer's failure to use updated or modified versions of the Software
// provided to Customer by AutoCore in order to avoid potential claims; (v)
// Software licensed for no fee, including trial, evaluation, or beta Software;
// or (vi) any modification of the Software by any party other than AUTOCORE, or
// an authorized third party agent of AUTOCORE.  If a temporary or permanent
// injunction is obtained against the use of any part of the Software for the
// reason that it infringes any third party's intellectual property rights,
// AutoCore will, at its option and expense, either (a) procure for Customer the
// right to continue to use the Software, (b) modify the Software so that it
// becomes non-infringing but remains in substantial compliance with the
// Documentation, or (c) terminate Customer's license to the affected Software
// and refund to Customer the Software Support fees, or the Subscription Fees,
// as applicable, paid for the remaining portion of the term of the affected
// license(s).  THE PROVISIONS OF THIS SECTION 5 STATE THE EXCLUSIVE LIABILITY
// OF AUTOCORE, AND THE EXCLUSIVE REMEDY OF CUSTOMER, WITH RESPECT TO ANY CLAIM
// OF INTELLECTUAL PROPERTY INFRINGEMENT.
//
// 6. Limitation of Liability.
//        6.1 Exclusion of Indirect Damages.  EXCEPT FOR DAMAGES CAUSED BY FRAUD
// OR A BREACH OF A PARTY'S CONFIDENTIALITY OBLIGATIONS, NEITHER PARTY (IN THE
// CASE OF AUTOCORE, INCLUDING ITS SUPPLIERS AND LICENSORS) IS OR WILL BE LIABLE
// TO THE OTHER FOR ANY INDIRECT, SPECIAL, INCIDENTAL AND/OR CONSEQUENTIAL
// DAMAGES, INCLUDING PUNITIVE OR MULTIPLE DAMAGES, OR ANY FAILURE TO REALIZE
// EXPECTED SAVINGS, LOSS OF DATA, EQUIPMENT DOWNTIME, LOSS OF USE, LOSS OF
// GOODWILL OR LOSS OF REVENUE OR PROFIT SUFFERED BY THE OTHER FOR ANY REASON,
// WHETHER FORESEEABLE OR NOT, NOR SHALL AutoCore BE LIABLE TO THE CUSTOMER FOR
// ANY CLAIM AGAINST CUSTOMER BY ANY THIRD PARTY FOR DAMAGES OF ANY KIND WHICH
// ARISE FROM OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE SOFTWARE OR
// THE DOCUMENTATION.
//        6.2 Limitation on Direct Damages.  EXCEPT FOR DAMAGES CAUSED BY FRAUD,
//        A
// BREACH OF A PARTY'S CONFIDENTIALITY OBLIGATIONS, OR INDEMNITY CLAIMS UNDER
// SECTION 5 HEREOF, IN NO EVENT SHALL EITHER PARTY'S TOTAL CUMULATIVE LIABILITY
// UNDER THIS AGREEMENT OR RELATING TO THE SUBJECT MATTER HEREOF FOR ALL CLAIMS,
// COSTS, LOSSES, AND DAMAGES EXCEED THE AMOUNT PAID OR PAYABLE BY CUSTOMER TO
// AutoCore PURSUANT TO THIS AGREEMENT FOR THE SOFTWARE.
//        6.3 Application of Exclusions and Limitations.  The foregoing
// limitations and exclusions of liability shall apply even if a party had been
// advised of the possibility of any such costs, losses or damages or knew or
// ought to have known of such costs, losses or damages and shall apply
// regardless of whether the action arose in contract, including, without
// limitation, from a fundamental breach, or breach of a condition, fundamental
// term or warranty, or in tort (including, without limitation negligence) or
// otherwise.  The foregoing provisions limiting the liability of AutoCore shall
// also apply to its officers, directors, employees, and agents as trust
// provisions for the benefit of such officers, directors, employees, and agents
// and shall be enforceable by such persons as trust beneficiaries.
//        6.4 Customer Data.  Customer acknowledges that the results of the
// Software depend on the data provided by Customer for use with the Software.
// Customer shall bear full responsibility for the accuracy of the data used
// with the Software.  Customer acknowledges that the Software is a tool to
// assist personnel in the analysis of software code and is not a substitute for
// personnel with expertise in such analysis.
//
// 7. Confidentiality.  By virtue of this Agreement, each party ("Recipient")
// may obtain, learn, develop, or have access to information that is
// confidential to the other party ("Discloser").  For purposes of this
// Agreement, "Confidential Information" will include any information that the
// Discloser identifies or marks as confidential or proprietary at the time of
// disclosure, or that reasonably appears to be proprietary or confidential in
// nature because of legends or other markings, the circumstances of disclosure,
// or the nature of the information itself.  "Confidential Information" will
// also include, but is not limited to, the Programs, Documentation, code,
// technology, know-how, ideas, algorithms, testing procedures, structure,
// interfaces, specifications, bugs, problem reports, any information or reports
// generated from the Software, analysis and performance information, the terms
// of this Agreement, including pricing terms, and other technical, business,
// product, marketing and financial information, plans, and data.  The Recipient
// will protect the Discloser's Confidential Information by using the same
// degree of care, but no less than a reasonable degree of care, as the
// Recipient uses to protect its own Confidential Information of a like nature
// against unauthorized use, disclosure, or publication, and will limit access
// to Confidential Information of the Discloser to those of its employees,
// contractors, and agents who need such access for purposes consistent with
// this Agreement and who are bound by law or contract to restrictions no less
// stringent than those herein.  The confidentiality obligations set forth in
// this Section 7 do not apply to Confidential Information that: (a) is
// generally known to the public through no improper action by Recipient or its
// third party agents; (b) was legitimately in Recipient's or its third party
// agent's possession prior to its disclosure by Discloser; (c) becomes
// available to Recipient, or to its third party agents, on a non-confidential
// basis from a source other than the Discloser or the Discloser's third party
// agents, provided that such source is not acting in violation of a
// confidentiality agreement with Discloser or with any of the Discloser's third
// party agents, or is otherwise prohibited from transmitting the information to
// the Recipient or to the Recipient's third party agents by a contractual,
// legal, or fiduciary obligation owed to the Discloser or to any of the
// Discloser's third party agents; or (d) was or is independently developed by
// or for Recipient or by the Recipient's third party agents without use of or
// reference to the Confidential Information.  If the Recipient is required to
// disclose any Confidential Information of the Discloser to a tribunal, or
// governmental or regulatory agency, then, unless the recipient is restricted
// by any law or order, the Recipient will provide the Discloser in advance of
// the disclosure to permit the Discloser to obtain protective orders
// maintaining the confidentiality of the Confidential Information.  At the
// Discloser's request and expense, Recipient agrees to provide reasonable
// assistance if the Discloser wishes to contest the disclosure.  Each Recipient
// will, within 10 days of termination of this Agreement, promptly deliver to
// the Discloser all documents, notes, or other physical embodiments of or
// reflecting the Confidential Information of Discloser (including copies
// thereof) that are in Recipient's possession or control (the "Documents"), and
// delete and destroy all electronic copies of the Documents, and provide
// written confirmation to Discloser of Recipient's compliance with the
// foregoing requirement.
//
// 8. Term and Termination.
//        8.1 This Agreement will commence on the date of the delivery of the
// Software and continue until terminated in accordance with the terms hereof.
// Unless earlier terminated as set forth in this Agreement, the term of each
// subscription license will be as set forth in the applicable invoice.
//        8.2 Either party will have the right to terminate this Agreement in
//        the
// event that the other party breaches its obligations hereunder.  Intent to
// terminate will be made by a written notice setting forth the details of the
// breach.  Termination will become effective 30 days from the date that the
// notification of intent to terminate was given, unless the breaching party has
// corrected the breach prior to the end of that 30-day period.  For purposes of
// clarity, if this Agreement is terminated pursuant to this Section 8.2, then
// such termination will not affect Customer's perpetual right to continue to
// use the Software if perpetual licenses of the Software were acquired by
// Customer.
//        8.3 AutoCore will have the right to terminate this Agreement effective
// immediately if: (a) Customer fails to meet its payment obligations under
// Section 3 of this Agreement, unless Customer has corrected such material
// breach within 10 days of Customer's receipt of written notice of such breach
// from AUTOCORE; or (b) Customer's violation of the restrictions set forth in
// Sections 2.2 - 2.4.
//        8.4 Either party will have the right to terminate this Agreement
// effective immediately if: (a) a petition of bankruptcy is granted against the
// other party; (b) the other party makes an assignment for the benefit of
// creditors; (c) the other party admits to being unable to meet its obligations
// as they come due; or (d) a petition of bankruptcy is filed by or against the
// other party and if such petition is not dismissed by the bankruptcy court
// within 60 days after its filing.  A party's intent to terminate this
// Agreement under this Section 8.4 will be made by a written notice to the
// other party.
//        8.5 If this Agreement is terminated pursuant to Section 8.3 or Section
// 8.4, then Customer will immediately (a) discontinue all use of the Programs
// and Documentation, (b) destroy the original and all copies of the Programs
// and the Documentation in its possession or control, and (c) provide written
// confirmation to AutoCore of its compliance with the foregoing requirements.
//        8.6 The parties' rights and obligations under Sections 2-9 of this
// Agreement survive any termination or expiration of this Agreement.
//
// 9. Miscellaneous.
//        9.1 Assignment.  This Agreement and the rights and obligations
//        hereunder
// are not transferable or assignable without the prior written consent of the
// other party hereto, with the exception of an assignment carried out as part
// of a merger, restructuring, or reorganization, or as a sale or transfer of
// all or substantially all of a party to this Agreements assets.  This
// Agreement inures to the benefit of, and is binding upon, the Parties and
// their respective heirs, legal representatives, permitted successors and
// permitted assigns
//        9.2 Applicable Law; Forum.  This Agreement will be governed by and
// construed in accordance with the law of Delaware.  This Agreement will not be
// governed by the United Nations Convention on Contracts for the International
// Sale of Goods.  Each of the parties agrees to submit to the exclusive
// jurisdiction of the federal courts in Delaware in respect of any dispute that
// arises out of or under this Agreement.
//        9.3 Amendments; Modification; Waiver; No Third Party Beneficiaries. No
// amendment or modification of this Agreement, nor any waiver of any rights
// hereunder, will be effective unless assented to in a writing signed by
// authorized representatives of both parties.  Any such waiver will be narrowly
// construed to apply only to the specific provision and under the specific
// circumstances for which it was given, and will not apply with respect to any
// repeated or continued violation of the same provision or any other provision.
// No other course of dealing between or among any of the parties to this
// Agreement or any delay in exercising any rights pursuant to this Agreement
// will operate as a waiver of any rights of any party to this Agreement. Except
// as expressly provided in this Agreement, no party who is not a party will
// have any right or obligation pursuant to this Agreement.
//        9.4 Equitable Remedies.  The parties recognize that money damages may
// not be an adequate remedy for any breach of any obligation hereunder by
// Customer involving AUTOCORE's intellectual property, Confidential
// Information, or use of the Software beyond the scope of the license granted
// by this Agreement.  The parties therefore agree that, in addition to any
// other remedies available hereunder, by law, or otherwise, AUTOCORE, and any
// third party from whom AutoCore has licensed software or technology, will be
// entitled to seek injunctive relief without the positing of a bond, as well as
// any other available equitable remedies, against any such continued breach by
// Customer of such obligations.
//        9.5 Severability.  If any provision of this Agreement is held invalid,
// illegal or otherwise unenforceable, such provision will be enforced as nearly
// as possible in accordance with the stated intention of the parties, and the
// enforceability of the remaining provisions of this Agreement will not be
// impaired thereby.  To the extent any provision cannot be enforced in
// accordance with the stated intentions of the parties, such provision will be
// deemed not to be a part of this Agreement.
//        9.6 Entire Agreement.  This Agreement, including all invoices
//        hereunder,
// constitutes the sole and entire agreement of the parties with respect to the
// subject matter hereof and supersedes and cancels any prior and
// contemporaneous oral or written proposals, promises, or agreements.  There
// are no promises, covenants or undertakings other than those expressly set
// forth in this Agreement.

#pragma once
#include "acfw/CommonDef.h"
#include <memory>
#include <vector>
#include <string>
#include <map>

ROOT_NAMESPACE_DECLARE

namespace core
{

class JsonValue;

class Json final
{
public:
    // Types
    enum Type
    {
        NUL,
        NUMBER,
        BOOL,
        STRING,
        ARRAY,
        OBJECT
    };

    // Array and Object typedefs
    typedef std::vector<Json> Array;
    typedef std::map<std::string, Json> Object;

    // Constructors for the various types of JSON value.
    Json() noexcept;  // NUL
    Json(std::nullptr_t) noexcept;  // NUL
    Json(double value);  // NUMBER
    Json(int64_t value);  // NUMBER
    Json(int value);  // NUMBER
    Json(bool value);  // BOOL
    Json(const std::string& value);  // STRING
    Json(std::string&& value);  // STRING
    Json(const char* value);  // STRING
    Json(const Array& values);  // ARRAY
    Json(Array&& values);  // ARRAY
    Json(const Object& values);  // OBJECT
    Json(Object&& values);  // OBJECT

    // Implicit constructor: anything with a toJson() function.
    template <class T, class = decltype(&T::toJson)>
    Json(const T& t)
        : Json(t.toJson())
    { }

    // This prevents Json(some_pointer) from accidentally producing a bool. Use
    // Json(bool(some_pointer)) if that behavior is desired.
    Json(void*) = delete;

    // Accessors
    Type type() const;

    bool isNull() const
    {
        return type() == NUL;
    }
    bool isNumber() const
    {
        return type() == NUMBER;
    }
    bool isBool() const
    {
        return type() == BOOL;
    }
    bool isString() const
    {
        return type() == STRING;
    }
    bool isArray() const
    {
        return type() == ARRAY;
    }
    bool isObject() const
    {
        return type() == OBJECT;
    }

    // Return the enclosed value if this is a number, 0 otherwise. Note that
    // json does not distinguish between integer and non-integer numbers -
    // numberValue() and intValue() can both be applied to a NUMBER-typed
    // Object.
    double numberValue() const;
    int64_t intValue() const;

    // Return the enclosed value if this is a boolean, false otherwise.
    bool boolValue() const;
    // Return the enclosed string if this is a string, "" otherwise.
    const std::string& stringValue() const;
    // Return the enclosed std::vector if this is an Array, or an empty vector
    // otherwise.
    const Array& arrayItems() const;
    // Return the enclosed std::map if this is an Object, or an empty map
    // otherwise.
    const Object& objectItems() const;

    // Return a reference to arr[i] if this is an Array, Json() otherwise.
    const Json& operator[](size_t i) const;
    // Return a reference to obj[key] if this is an Object, Json() otherwise.
    const Json& operator[](const std::string& key) const;

    // Serialize.
    void dump(std::string& out) const;
    std::string dump() const
    {
        std::string out;
        dump(out);
        return out;
    }

    // Parse. If parse fails, return Json() and assign an error message to err.
    static Json parse(const std::string& in, std::string& err);
    static Json parse(const char* in, std::string& err)
    {
        if (in)
        {
            return parse(std::string(in), err);
        }
        else
        {
            err = "null input";
            return nullptr;
        }
    }
    // Parse multiple objects, concatenated or separated by whitespace
    static std::vector<Json> parseMulti(const std::string& in,
        std::string::size_type& parserStopPos,
        std::string& err);

    static inline std::vector<Json> parseMulti(const std::string& in,
        std::string& err)
    {
        std::string::size_type parserStopPos;
        return parseMulti(in, parserStopPos, err);
    }

    bool operator==(const Json& rhs) const;
    bool operator<(const Json& rhs) const;
    bool operator!=(const Json& rhs) const
    {
        return !(*this == rhs);
    }
    bool operator<=(const Json& rhs) const
    {
        return !(rhs < *this);
    }
    bool operator>(const Json& rhs) const
    {
        return (rhs < *this);
    }
    bool operator>=(const Json& rhs) const
    {
        return !(*this < rhs);
    }

private:
    std::shared_ptr<JsonValue> m_ptr;
};

// Internal class hierarchy - JsonValue objects are not exposed to users of this
// API.
class JsonValue
{
protected:
    friend class Json;
    friend class JsonInt;
    friend class JsonDouble;
    virtual Json::Type type() const                   = 0;
    virtual bool equals(const JsonValue* other) const = 0;
    virtual bool less(const JsonValue* other) const   = 0;
    virtual void dump(std::string& out) const         = 0;
    virtual double numberValue() const;
    virtual int64_t intValue() const;
    virtual bool boolValue() const;
    virtual const std::string& stringValue() const;
    virtual const Json::Array& arrayItems() const;
    virtual const Json& operator[](size_t i) const;
    virtual const Json::Object& objectItems() const;
    virtual const Json& operator[](const std::string& key) const;
    virtual ~JsonValue()
    { }
};
}  // namespace core
ROOT_NAMESPACE_END
